# docker compose format you wish to use
version: '3'

services:
  product-service:
    build: products
    volumes:
      - ./products:/usr/src/app
    ports:
      - 5002:80

  www:
    image: php:apache
    volumes:
      - ./web:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - product-service